kind = "web"
previewPath = "/"
title = "VaultTrace"
version = "1.0.0"
id = "artifacts/vaulttrace"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24065

[services.development]
run = "pnpm --filter @workspace/vaulttrace run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/vaulttrace", "run", "build" ]
publicDir = "artifacts/vaulttrace/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24065"
BASE_PATH = "/"
